PINECONE_API_KEY="4bdccaca-1789-427c-bd9c-84839308a05e"
OPENAI_API_KEY="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"
PINECONE_INDEX_NAME="poc-vessel-manag"
MONGODB_CONNECTION_STRING="mongodb+srv://newuser:newpassword@cluster0.o7p352n.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"